spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/orderdb
    username: admin
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate